# Generated by Django 2.2.6 on 2019-10-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Нет', max_length=15)),
                ('position', models.CharField(default='Нет', max_length=35)),
                ('name', models.CharField(default='Нет', max_length=30)),
                ('phone', models.CharField(default='Нет', max_length=20)),
                ('email', models.CharField(default='Нет', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['g_name'],
            },
        ),
        migrations.CreateModel(
            name='Icinga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='root', max_length=15)),
                ('password', models.CharField(default='root', max_length=15)),
                ('protocol', models.CharField(default='https', max_length=10)),
                ('ip', models.CharField(default='192.168.0.1', max_length=15)),
                ('port', models.CharField(default='5665', max_length=6)),
            ],
            options={
                'verbose_name': 'Настройки доступа к Icinga',
                'verbose_name_plural': 'Настройки доступа к Icinga',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['p_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'ordering': ['s_name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.CharField(max_length=10)),
                ('h_name', models.CharField(max_length=70)),
                ('h_online', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Groups')),
                ('project', models.ManyToManyField(related_name='project', to='monitoring.Project')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['h_name'],
            },
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_ip', models.CharField(max_length=15)),
                ('c_status', models.IntegerField()),
                ('c_table', models.IntegerField()),
                ('c_time', models.FloatField()),
                ('c_comment', models.CharField(default='Нет', max_length=100)),
                ('c_online', models.BooleanField()),
                ('c_trable', models.CharField(default='Нет', max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Host')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='monitoring.Service')),
            ],
            options={
                'verbose_name': 'Канал связи',
                'verbose_name_plural': 'Каналы связи',
                'ordering': ['host'],
            },
        ),
    ]
